services:
  ncm-api:
    image: moefurina/ncm-api:latest
    environment:
      - ENABLE_GENERAL_UNBLOCK=false
    restart: unless-stopped
  app:
    build:
      context: .
      args:
        VITE_REAL_IP: ${VITE_REAL_IP}
    depends_on: [ncm-api]
    ports: ["80:80"]
    environment:
      - NCM_BASE=http://ncm-api:3000
      - NCM_MUSIC_U=${NCM_MUSIC_U}
      - COOKIE_PATH=/data/cookie
    volumes:
      - cookie-data:/data
    restart: unless-stopped
volumes:
  cookie-data:
